# Generated by Django 5.2.1 on 2025-06-04 12:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=300)),
                ('is_published', models.BooleanField(default=False)),
                ('registration_open_date', models.DateTimeField(blank=True, null=True)),
                ('registration_close_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('number', 'Number'), ('date', 'Date'), ('textarea', 'Textarea'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox'), ('select', 'Select Dropdown'), ('file', 'File Upload'), ('phone', 'Phone Number')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('choices', models.TextField(blank=True, help_text='For radio, checkbox, select fields. Enter choices separated by newlines.')),
                ('placeholder', models.CharField(blank=True, max_length=100)),
                ('help_text', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='events.event')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('event', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('attended', 'Attended'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('participant_name', models.CharField(blank=True, max_length=200)),
                ('participant_email', models.EmailField(blank=True, max_length=254)),
                ('participant_phone', models.CharField(blank=True, max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationFormFieldData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field_value', models.TextField()),
                ('event_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventfield')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_data', to='events.registration')),
            ],
            options={
                'unique_together': {('registration', 'event_field')},
            },
        ),
    ]
