# Generated by Django 5.2.1 on 2025-06-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfield',
            name='is_participant_email',
            field=models.BooleanField(default=False, help_text='Use this field as participant email'),
        ),
        migrations.AddField(
            model_name='eventfield',
            name='is_participant_name',
            field=models.BooleanField(default=False, help_text='Use this field as participant name'),
        ),
        migrations.AddField(
            model_name='eventfield',
            name='is_participant_phone',
            field=models.BooleanField(default=False, help_text='Use this field as participant phone'),
        ),
    ]
