# Generated by Django 5.2.1 on 2025-06-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventfield_is_participant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional event image', null=True, upload_to='event_images/'),
        ),
    ]
